### ISSUE TITLE
Create a file listing Spark errors when executing scripts

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/data-analyses-scheduler#38]
When a script is submitted to Spark, we check the output log (from standard error) to identify the presence of certain errors. For convenience, create a file storing a list of the possible error messages that could show up on the log, and read that file in the spark tasks sender to check for the presence of any of those error messages in the logs.

Also refer to the following issue for a consequence of the problem: https://github.com/benchflow/data-analyses-scheduler/issues/82

See also: https://github.com/benchflow/data-analyses-scheduler/issues/87#issuecomment-241706201

**Comment by VincenzoFerme** [comment]
@Cerfoglg The following is an error that is not catched and visualised:

``` python
<al[*] /app/analysers/trials/io.py local[*] cassandra camundaXZ_XZ 92d6b5d3039f370f807b1ae1ba79865bb277c0abe531656501ce3afcb75ef23c
Traceback (most recent call last):
  File "/app/analysers/trials/io.py", line 3, in <module>
    import io
  File "/app/analysers/trials/io.py", line 4, in <module>
    import gzip
  File "/usr/lib/python2.7/gzip.py", line 36, in <module>
    class GzipFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'
```

**Comment by VincenzoFerme** [comment]
Other errors that occurred randomly:

``` python
Traceback (most recent call last):
  File "/app/data-transformers/transformers/statsTransformer.py", line 150, in <module>
    query.saveToCassandra(cassandraKeyspace, "environment_data", ttl=timedelta(hours=1))
  File "/usr/spark/pyspark-cassandra-assembly-0.2.7.jar/pyspark_cassandra/rdd.py", line 91, in saveToCassandra
  File "/usr/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/usr/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o32.saveToCassandra.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1, localhost): net.razorvine.pickle.PickleException: failed to __setstate__()
    at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:337)
    at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:192)
    at net.razorvine.pickle.Unpickler.load(Unpickler.java:85)
    at net.razorvine.pickle.Unpickler.loads(Unpickler.java:98)
    at pyspark_util.BatchUnpickler.apply(Pickling.scala:128)
    at pyspark_util.BatchUnpickler.apply(Pickling.scala:126)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at com.datastax.spark.connector.util.CountingIterator.hasNext(CountingIterator.scala:12)
    at com.datastax.spark.connector.writer.GroupingBatchBuilder.hasNext(GroupingBatchBuilder.scala:101)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
    at com.datastax.spark.connector.writer.TableWriter$$anonfun$write$1.apply(TableWriter.scala:155)
    at com.datastax.spark.connector.writer.TableWriter$$anonfun$write$1.apply(TableWriter.scala:139)
    at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:110)
    at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:109)
    at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:139)
    at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:109)
    at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:139)
    at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:37)
    at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:37)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:88)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:335)
    ... 25 more
Caused by: java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
    at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:412)
    at pyspark_util.UUIDHolder.__setstate__(Pickling.scala:191)
    ... 29 more

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1496)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1458)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1447)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:567)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1822)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1835)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1912)
    at com.datastax.spark.connector.RDDFunctions.saveToCassandra(RDDFunctions.scala:37)
    at pyspark_cassandra.PythonHelper.saveToCassandra(PythonHelper.scala:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
    at py4j.Gateway.invoke(Gateway.java:259)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:207)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.razorvine.pickle.PickleException: failed to __setstate__()
    at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:337)
    at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:192)
    at net.razorvine.pickle.Unpickler.load(Unpickler.java:85)
    at net.razorvine.pickle.Unpickler.loads(Unpickler.java:98)
    at pyspark_util.BatchUnpickler.apply(Pickling.scala:128)
    at pyspark_util.BatchUnpickler.apply(Pickling.scala:126)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at com.datastax.spark.connector.util.CountingIterator.hasNext(CountingIterator.scala:12)
    at com.datastax.spark.connector.writer.GroupingBatchBuilder.hasNext(GroupingBatchBuilder.scala:101)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
    at com.datastax.spark.connector.writer.TableWriter$$anonfun$write$1.apply(TableWriter.scala:155)
    at com.datastax.spark.connector.writer.TableWriter$$anonfun$write$1.apply(TableWriter.scala:139)
    at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:110)
    at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:109)
    at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:139)
    at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:109)
    at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:139)
    at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:37)
    at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:37)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:88)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:335)
    ... 25 more
Caused by: java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
    at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:412)
    at pyspark_util.UUIDHolder.__setstate__(Pickling.scala:191)
    ... 29 more
```

``` python
16/03/12 11:55:57 ERROR Executor: Exception in task 38.0 in stage 0.0 (TID 38)
net.razorvine.pickle.PickleException: failed to __setstate__()
    at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:337)
    at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:192)
    at net.razorvine.pickle.Unpickler.load(Unpickler.java:85)
    at net.razorvine.pickle.Unpickler.loads(Unpickler.java:98)
    at pyspark_util.BatchUnpickler.apply(Pickling.scala:128)
    at pyspark_util.BatchUnpickler.apply(Pickling.scala:126)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at com.datastax.spark.connector.util.CountingIterator.hasNext(CountingIterator.scala:12)
    at com.datastax.spark.connector.writer.GroupingBatchBuilder.hasNext(GroupingBatchBuilder.scala:101)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
    at com.datastax.spark.connector.writer.TableWriter$$anonfun$write$1.apply(TableWriter.scala:155)
    at com.datastax.spark.connector.writer.TableWriter$$anonfun$write$1.apply(TableWriter.scala:139)
    at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:110)
    at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:109)
    at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:139)
    at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:109)
    at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:139)
    at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:37)
    at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:37)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:88)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:335)
    ... 25 more
Caused by: java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:506)
    at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:412)
    at pyspark_util.UUIDHolder.__setstate__(Pickling.scala:191)
    ... 29 more
```

``` python
ERROR ContextCleaner: Error cleaning broadcast 12
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
    at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:208)
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
    at scala.concurrent.Await$.result(package.scala:107)
    at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcEnv.scala:241)
    at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:101)
    at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:77)
    at org.apache.spark.storage.BlockManagerMaster.removeBroadcast(BlockManagerMaster.scala:128)
    at org.apache.spark.broadcast.TorrentBroadcast$.unpersist(TorrentBroadcast.scala:228)
    at org.apache.spark.broadcast.TorrentBroadcastFactory.unbroadcast(TorrentBroadcastFactory.scala:45)
    at org.apache.spark.broadcast.BroadcastManager.unbroadcast(BroadcastManager.scala:67)
    at org.apache.spark.ContextCleaner.doCleanupBroadcast(ContextCleaner.scala:214)
    at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:170)
    at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:161)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:161)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1136)
    at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:154)
    at org.apache.spark.ContextCleaner$$anon$3.run(ContextCleaner.scala:67)
```

``` python
jar --py-files /usr/spark/pyspark-cassandra-assembly-0.2.7.jar --master local[*] /app/analysers/trials/cpu.py local[*] cassandra camundaZZPY_ZZPY stats_camunda]
Traceback (most recent call last):
  File "/app/analysers/trials/databaseSize.py", line 29, in <module>
    .reduce(lambda a, b: a["size"]+b["size"])
  File "/usr/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 802, in reduce
ValueError: Can not reduce() empty RDD
None
None

Script /app/analysers/trials/databaseSize.py processed
None
0
Traceback (most recent call last):
  File "/app/analysers/trials/cpu.py", line 66, in <module>
    .where("trial_id=? AND experiment_id=? AND container_id=?", trialID, experimentID, containerID) \
  File "/usr/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1320, in first
ValueError: RDD is empty
Traceback (most recent call last):
  File "/app/analysers/trials/ram.py", line 53, in <module>
    highestCount = data[0][0]        
IndexError: list index out of range
None
None
Traceback (most recent call last):
  File "/app/analysers/trials/throughput.py", line 100, in <module>
    delta = largest - smallest
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

``` python
Script /app/analysers/trials/numberOfProcessInstances.py processed
Traceback (most recent call last):
  File "/app/analysers/trials/processDuration.py", line 93, in <module>
    highestCount = data[0][0]        
IndexError: list index out of range
[Stage 3:=================================>                      (29 + 19) / 48]

Script /app/analysers/trials/processDuration.py processed
Traceback (most recent call last):
  File "/app/analysers/trials/cpu.py", line 66, in <module>
    .where("trial_id=? AND experiment_id=? AND container_id=?", trialID, experimentID, containerID) \
  File "/usr/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1320, in first
ValueError: RDD is empty
Traceback (most recent call last):
  File "/app/analysers/trials/ram.py", line 53, in <module>
    highestCount = data[0][0]        
IndexError: list index out of range
```

```
spark-tasks-sender-1 | 2016-03-19T09:17:03.972162886Z Script /app/analysers/trials/IO.py processed
spark-tasks-sender-1 | 2016-03-19T09:17:04.998519933Z  [Stage 3:======================================================>  (46 + 2) / 48]                                                                                  16/03/19 10:17:04 ERROR ContextCleaner: Error cleaning broadcast 3
spark-tasks-sender-1 | 2016-03-19T09:17:04.998583007Z java.lang.InterruptedException
spark-tasks-sender-1 | 2016-03-19T09:17:04.998592480Z   at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998600332Z   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:208)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998607941Z   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998614886Z   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998621949Z   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998628878Z   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998635841Z   at scala.concurrent.Await$.result(package.scala:107)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998642853Z   at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcEnv.scala:241)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998649739Z   at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:101)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998656725Z   at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:77)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998687341Z   at org.apache.spark.storage.BlockManagerMaster.removeBroadcast(BlockManagerMaster.scala:128)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998695729Z   at org.apache.spark.broadcast.TorrentBroadcast$.unpersist(TorrentBroadcast.scala:228)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998709957Z   at org.apache.spark.broadcast.TorrentBroadcastFactory.unbroadcast(TorrentBroadcastFactory.scala:45)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998717138Z   at org.apache.spark.broadcast.BroadcastManager.unbroadcast(BroadcastManager.scala:67)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998723965Z   at org.apache.spark.ContextCleaner.doCleanupBroadcast(ContextCleaner.scala:214)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998731060Z   at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:170)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998738306Z   at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:161)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998745440Z   at scala.Option.foreach(Option.scala:236)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998752535Z   at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:161)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998759885Z   at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1136)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998766660Z   at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:154)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998773774Z   at org.apache.spark.ContextCleaner$$anon$3.run(ContextCleaner.scala:67)
spark-tasks-sender-1 | 2016-03-19T09:17:04.998780612Z 
spark-tasks-sender-1 | 2016-03-19T09:17:04.999057347Z Script /app/analysers/trials/ram.py failed
spark-tasks-sender-1 | 2016-03-19T09:17:04.999072669Z  [Stage 3:======================================================>  (46 + 2) / 48]                                                                                  16/03/19 10:17:04 ERROR ContextCleaner: Error cleaning broadcast 3
spark-tasks-sender-1 | 2016-03-19T09:17:04.999081280Z java.lang.InterruptedException
spark-tasks-sender-1 | 2016-03-19T09:17:04.999088366Z   at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999095500Z   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:208)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999102587Z   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999109534Z   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999116489Z   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999123494Z   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999130419Z   at scala.concurrent.Await$.result(package.scala:107)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999137273Z   at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcEnv.scala:241)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999152211Z   at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:101)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999168753Z   at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:77)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999176876Z   at org.apache.spark.storage.BlockManagerMaster.removeBroadcast(BlockManagerMaster.scala:128)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999183893Z   at org.apache.spark.broadcast.TorrentBroadcast$.unpersist(TorrentBroadcast.scala:228)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999190795Z   at org.apache.spark.broadcast.TorrentBroadcastFactory.unbroadcast(TorrentBroadcastFactory.scala:45)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999197637Z   at org.apache.spark.broadcast.BroadcastManager.unbroadcast(BroadcastManager.scala:67)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999204451Z   at org.apache.spark.ContextCleaner.doCleanupBroadcast(ContextCleaner.scala:214)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999211445Z   at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:170)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999218867Z   at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:161)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999225961Z   at scala.Option.foreach(Option.scala:236)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999232726Z   at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:161)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999239755Z   at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1136)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999256457Z   at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:154)
spark-tasks-sender-1 | 2016-03-19T09:17:04.999264192Z   at org.apache.spark.ContextCleaner$$anon$3.run(ContextCleaner.scala:67)
```
